In [151]:
import numpy as np
import math
a=np.array([(1,2,3,4,5,6,7,8,9),(5,6,7,8,2,3,4,5,5)],dtype='int32')
print(a)

[[1 2 3 4 5 6 7 8 9]
 [5 6 7 8 2 3 4 5 5]]


In [152]:
a.dtype,a.ndim,a.shape

(dtype('int32'), 2, (2, 9))

In [153]:
a[1,-2],a[0:],a[1,1:-1:2]

(5, array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 6, 7, 8, 2, 3, 4, 5, 5]]), array([6, 8, 3, 5]))

In [154]:
a[1,2]=3
print(a)

[[1 2 3 4 5 6 7 8 9]
 [5 6 3 8 2 3 4 5 5]]


In [155]:
a[:,4]=(100,200)
print(a)

[[  1   2   3   4 100   6   7   8   9]
 [  5   6   3   8 200   3   4   5   5]]


In [156]:
b=np.array([[(1,2,3,4),(11,12,13,14)],[(5,6,7,8),(9,10,11,12)],[(23,23,43,42),(33,44,55,22)]])
print(b),b.shape 

[[[ 1  2  3  4]
  [11 12 13 14]]

 [[ 5  6  7  8]
  [ 9 10 11 12]]

 [[23 23 43 42]
  [33 44 55 22]]]


(None, (3, 2, 4))

In [157]:
b.size

24

In [158]:
b[:,0,1:]=[(34,23,5),(45,43,6),(43,54,7)]
print(b)

[[[ 1 34 23  5]
  [11 12 13 14]]

 [[ 5 45 43  6]
  [ 9 10 11 12]]

 [[23 43 54  7]
  [33 44 55 22]]]


In [159]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [160]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [161]:
a=np.full((7,3),44,dtype='float32')
a[1,-2]=13
print(a)

[[44. 44. 44.]
 [44. 13. 44.]
 [44. 44. 44.]
 [44. 44. 44.]
 [44. 44. 44.]
 [44. 44. 44.]
 [44. 44. 44.]]


In [162]:
np.full_like(a,4)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]], dtype=float32)

In [163]:
np.random.rand()

0.003186520263659287

In [164]:
np.random.random_sample(a.shape)

array([[0.11755854, 0.99033164, 0.91865408],
       [0.73319832, 0.3996018 , 0.66806616],
       [0.60117662, 0.99069368, 0.45205163],
       [0.74140016, 0.64906905, 0.01289624],
       [0.47169141, 0.93848907, 0.68825389],
       [0.44909934, 0.25542154, 0.11633362],
       [0.41113592, 0.44953035, 0.6328473 ]])

In [165]:
np.random.randint(-4,10,size=(3,3))

array([[ 2, -2,  2],
       [ 0,  4,  1],
       [ 1, -4,  6]])

In [166]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [176]:
tut=np.full((5,5),1)
print(tut)
tut[1:4]=np.zeros((3,5))
tut[2,2]=9
print(tut)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 9 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]]


In [177]:
d=np.array([1,2,3])
e=d.copy()
e[0]=6
print(e)

[6 2 3]


In [178]:
print(d)

[1 2 3]


In [179]:
a=np.array([1,2,3,4])
print(a)
a+2
a-2
a*2
a/2

[1 2 3 4]


array([0.5, 1. , 1.5, 2. ])

In [183]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [201]:
a=np.full((3,4),5,dtype='int32')
print(a)
b=np.ones((4,7),dtype='int32')
print(b)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [204]:
np.matmul(a,b)

array([[20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20]])

In [213]:
c=np.identity(5)
np.linalg.det(c)

1.0

In [215]:
stats=np.array([(1,2,3,),(4,5,6)])

In [216]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [218]:
np.min(stats),np.max(stats),np.max(stats,axis=1)

(1, 6, array([3, 6]))

In [ ]:
np