In [7]:
import numpy as np
a=np.array([(1,2,3),(4,5,6),(7,8,9),(45,86,9),(7,5,4)])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [45 86  9]
 [ 7  5  4]]


In [8]:
import time 
import sys 
s=range(1000)
print(sys.getsizeof(s)*len(s))


48000


In [11]:
d=np.arange(1000)
print(d.size*d.itemsize)

4000


In [1]:
size=1000000000
l1=range(size)
l2=range(size)
a1=np.arange(size)
a2=np.arange(size)
start=time.time()
result=[(x,y) for x,y in zip(l1,l2)]


NameError: name 'np' is not defined